param([string]$Ffmpeg = 'C:\Windows\ffmpeg.exe')
$ErrorActionPreference = 'Stop'
$workspace = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$mediaDirectory = Join-Path $workspace 'app\godot\media'
$fixtureDirectory = Join-Path $workspace 'tests\fixtures'
New-Item -ItemType Directory -Path $mediaDirectory -Force | Out-Null
New-Item -ItemType Directory -Path $fixtureDirectory -Force | Out-Null
if (-not (Test-Path -LiteralPath $Ffmpeg)) { throw 'Pass -Ffmpeg <ffmpeg.exe> to generate the synthetic C03 fixture.' }
$output = Join-Path $mediaDirectory 'c03_sbs_grid.mp4'
$filter = "drawbox=x=0:y=0:w=960:h=1080:color=red:t=fill,drawbox=x=960:y=0:w=960:h=1080:color=blue:t=fill,drawgrid=w=240:h=180:t=4:c=white@0.6,drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='LEFT - TOP':x=80:y=60:fontsize=72:fontcolor=white,drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='RIGHT - TOP':x=1040:y=60:fontsize=72:fontcolor=white,drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='BOTTOM':x=80:y=920:fontsize=72:fontcolor=yellow,drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='BOTTOM':x=1040:y=920:fontsize=72:fontcolor=yellow,drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='FRAME %{n}':x=300:y=480:fontsize=60:fontcolor=white,drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='FRAME %{n}':x=1260:y=480:fontsize=60:fontcolor=white"
$arguments = @('-hide_banner','-loglevel','error','-y','-f','lavfi','-i','color=c=black:s=1920x1080:r=30:d=6',
    '-f','lavfi','-i','sine=frequency=440:sample_rate=48000:duration=6','-vf',$filter,
    '-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-profile:v','high',
    '-color_primaries','bt709','-color_trc','bt709','-colorspace','bt709',
    '-c:a','aac','-b:a','96k','-movflags','+faststart','-shortest',$output)
& $Ffmpeg @arguments
if ($LASTEXITCODE -ne 0) { throw 'C03 fixture encoding failed.' }
& $Ffmpeg -hide_banner -loglevel error -i $output -f null NUL
if ($LASTEXITCODE -ne 0) { throw 'C03 fixture decode verification failed.' }
$version = (& $Ffmpeg -version | Select-Object -First 1)
[ordered]@{
    schema_version = 1
    name = 'c03_sbs_grid'
    source = 'Synthetic red/blue labelled grid generated by tools/media/Generate-C03Fixtures.ps1'
    rights = 'Project-generated calibration graphics and tone; no external media'
    file = 'app/godot/media/c03_sbs_grid.mp4'
    bytes = (Get-Item -LiteralPath $output).Length
    sha256 = (Get-FileHash -LiteralPath $output -Algorithm SHA256).Hash.ToLowerInvariant()
    ffmpeg = $version
    width = 1920
    height = 1080
    fps = 30
    frames = 180
    duration_seconds = 6
    video = 'H.264 high, yuv420p, BT.709 SDR'
    audio = 'AAC 48 kHz mono 440 Hz tone'
    stereo = 'SBS: left red, right blue; equal half rectangles'
    expected = @('TOP text above BOTTOM', 'Left eye red / right eye blue in SBS mode', 'Frame counters increase together', '2D shows both halves', 'Tone pauses with playback')
    android_validation = 'not_run'
} | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $fixtureDirectory 'c03_sbs_grid.json') -Encoding utf8
Write-Output "Generated and decoded: $output"
